INSERT INTO Questions (question_text, answer_index, options, certification_code) VALUES
('Which AWS service provides a content delivery network to distribute content globally with low latency?', 1, 'A. AWS RDS,B. Amazon CloudFront,C. AWS S3,D. AWS Elastic Beanstalk', 'AWS-CCP'),
('What type of pricing model does AWS use to charge customers?', 2, 'A. Fixed subscription,B. Pay-as-you-go,C. Contract-based,D. Usage-based with fixed fees', 'AWS-CCP'),
('What is the primary benefit of Amazon S3?', 1, 'A. Compute power,B. Scalable storage,C. Networking,D. Database management', 'AWS-CCP'),
('Which service is used for monitoring AWS resources?', 0, 'A. Amazon CloudWatch,B. Amazon EC2,C. AWS Lambda,D. Amazon RDS', 'AWS-CCP'),
('Which AWS service provides a relational database managed by AWS?', 3, 'A. Amazon S3,B. Amazon EC2,C. AWS Lambda,D. Amazon RDS', 'AWS-CCP'),
('What is the purpose of Amazon VPC?', 0, 'A. To create an isolated network for resources,B. To manage databases,C. To store files,D. To monitor applications', 'AWS-CCP'),
('Which AWS service allows you to run code without provisioning or managing servers?', 2, 'A. Amazon EC2,B. Amazon RDS,C. AWS Lambda,D. AWS S3', 'AWS-CCP'),
('What does IAM stand for in AWS?', 2, 'A. Instant Access Management,B. Initial Account Management,C. Identity and Access Management,D. Identity Account Management', 'AWS-CCP'),
('Which service offers an interactive user interface for managing AWS resources?', 3, 'A. AWS CLI,B. AWS API,C. AWS SDK,D. AWS Management Console', 'AWS-CCP'),
('What is the main function of Amazon Route 53?', 0, 'A. Domain Name System (DNS) service,B. Web hosting,C. Security management,D. Network monitoring', 'AWS-CCP'),
('Which AWS service is used to analyze and visualize log data?', 1, 'A. Amazon RDS,B. Amazon CloudWatch Logs,C. Amazon VPC,D. AWS IAM', 'AWS-CCP'),
('Which tool provides billing and cost management in AWS?', 0, 'A. AWS Cost Explorer,B. AWS IAM,C. AWS Lambda,D. Amazon RDS', 'AWS-CCP'),
('What is the main use of Amazon EC2?', 1, 'A. Storage,B. Virtual server hosting,C. Networking,D. Data analytics', 'AWS-CCP'),
('Which service provides managed DDoS protection?', 2, 'A. AWS Shield Advanced,B. AWS VPC,C. AWS Shield,D. AWS IAM', 'AWS-CCP'),
('What is a key feature of Amazon RDS?', 3, 'A. Object storage,B. Content delivery,C. Security,D. Managed relational databases', 'AWS-CCP'),
('Which AWS service provides scalable object storage?', 0, 'A. Amazon S3,B. Amazon EC2,C. AWS Lambda,D. Amazon DynamoDB', 'AWS-CCP'),
('Which AWS service helps with setting up a private network for your AWS resources?', 0, 'A. Amazon VPC,B. Amazon CloudFront,C. AWS Lambda,D. AWS S3', 'AWS-CCP'),
('Which AWS service offers distributed denial of service (DDoS) protection?', 2, 'A. Amazon CloudFront,B. Amazon RDS,C. AWS Shield,D. Amazon S3', 'AWS-CCP'),
('What does Amazon S3 stand for?', 1, 'A. Simple Storage Service,B. Secure Storage Service,C. Storage Support System,D. Scalable Storage Solution', 'AWS-CCP'),
('Which AWS service is used for deploying and managing containers?', 0, 'A. Amazon ECS,B. AWS Lambda,C. Amazon S3,D. Amazon RDS', 'AWS-CCP'),
('Which AWS service is used for machine learning model training and deployment?', 1, 'A. AWS Lambda,B. Amazon SageMaker,C. Amazon RDS,D. AWS S3', 'AWS-CCP'),
('Which AWS service provides serverless computing?', 2, 'A. Amazon EC2,B. Amazon RDS,C. AWS Lambda,D. Amazon S3', 'AWS-CCP'),
('Which AWS service provides a managed NoSQL database?', 0, 'A. Amazon DynamoDB,B. Amazon RDS,C. Amazon EC2,D. AWS S3', 'AWS-CCP'),
('What is the main purpose of Amazon CloudFront?', 3, 'A. Data storage,B. Compute power,C. Network isolation,D. Content delivery', 'AWS-CCP'),
('Which service allows users to manage user permissions and credentials?', 0, 'A. AWS IAM,B. AWS S3,C. Amazon CloudWatch,D. AWS Lambda', 'AWS-CCP'),
('Which AWS service offers a database for document-based data models?', 1, 'A. Amazon RDS,B. Amazon DynamoDB,C. AWS Lambda,D. Amazon S3', 'AWS-CCP'),
('What type of database is Amazon DynamoDB?', 3, 'A. Relational,B. SQL-based,C. In-memory,D. NoSQL', 'AWS-CCP'),
('Which AWS service would you use to store large amounts of data at low cost?', 2, 'A. Amazon RDS,B. AWS Lambda,C. Amazon S3,D. AWS IAM', 'AWS-CCP'),
('Which AWS service helps secure your applications from DDoS attacks?', 1, 'A. Amazon EC2,B. AWS Shield,C. Amazon S3,D. Amazon VPC', 'AWS-CCP'),
('Which AWS service allows you to host a scalable web application?', 2, 'A. Amazon CloudWatch,B. AWS IAM,C. Amazon EC2,D. AWS Lambda', 'AWS-CCP'),
('What is the primary use of Amazon RDS?', 1, 'A. Object storage,B. Relational database hosting,C. Network management,D. Content delivery', 'AWS-CCP'),
('Which AWS service helps detect unauthorized activity in your account?', 2, 'A. AWS IAM,B. AWS S3,C. Amazon GuardDuty,D. Amazon RDS', 'AWS-CCP'),
('What does Amazon S3 Glacier offer?', 3, 'A. Real-time data access,B. Web hosting,C. Fast file retrieval,D. Long-term, low-cost storage', 'AWS-CCP'),
('What is a benefit of using AWS Lambda?', 1, 'A. Persistent storage,B. Serverless architecture,C. Managed databases,D. Virtual networking', 'AWS-CCP'),
('What is Amazon EBS used for?', 0, 'A. Persistent storage for EC2 instances,B. DNS management,C. Content delivery,D. NoSQL database hosting', 'AWS-CCP'),
('Which AWS service is used to securely connect an on-premises network to AWS?', 2, 'A. Amazon S3,B. AWS Lambda,C. AWS Direct Connect,D. Amazon CloudFront', 'AWS-CCP'),
('What is Amazon CloudTrail primarily used for?', 0, 'A. Tracking API calls and user actions,B. Serverless computing,C. Content delivery,D. Database management', 'AWS-CCP'),
('Which AWS service is used for real-time data processing?', 2, 'A. AWS IAM,B. AWS RDS,C. Amazon Kinesis,D. AWS S3', 'AWS-CCP'),
('What type of storage does Amazon S3 provide?', 1, 'A. Block storage,B. Object storage,C. File storage,D. Archival storage', 'AWS-CCP'),
('Which AWS service helps detect and analyze security threats?', 3, 'A. AWS S3,B. AWS IAM,C. AWS Lambda,D. Amazon GuardDuty', 'AWS-CCP'),
('What does the AWS Free Tier provide?', 1, 'A. Unlimited free services,B. Limited-time free usage of some services,C. No-cost access to premium features,D. Always free, unlimited usage of resources', 'AWS-CCP'),
('Which service is a fully managed data warehouse in AWS?', 2, 'A. Amazon RDS,B. Amazon S3,C. Amazon Redshift,D. AWS Lambda', 'AWS-CCP'),
('Which AWS service can distribute traffic across multiple EC2 instances?', 3, 'A. Amazon S3,B. AWS RDS,C. Amazon VPC,D. Elastic Load Balancing', 'AWS-CCP'),
('What is a benefit of using Amazon EC2 Auto Scaling?', 0, 'A. Automatically adjust capacity to demand,B. Host static websites,C. Run serverless code,D. Manage user accounts', 'AWS-CCP'),
('What is the purpose of Amazon SNS?', 2, 'A. Database hosting,B. Virtual server hosting,C. Sending notifications,D. Content delivery', 'AWS-CCP'),
('Which AWS service offers version control for code?', 0, 'A. AWS CodeCommit,B. AWS Lambda,C. AWS S3,D. Amazon RDS', 'AWS-CCP'),
('Which tool helps optimize AWS costs by providing recommendations?', 3, 'A. Amazon RDS,B. Amazon S3,C. AWS Lambda,D. AWS Trusted Advisor', 'AWS-CCP'),
('Which service provides content delivery network to distribute content globally with low latency?', 1, 'A. AWS RDS,B. Amazon CloudFront,C. AWS S3,D. AWS Elastic Beanstalk', 'AWS-CCP'),
('Which AWS service provides an isolated network environment where resources can be deployed?', 0, 'A. Amazon VPC,B. Amazon RDS,C. AWS Lambda,D. Amazon CloudFront', 'AWS-CCP'),
('What feature of Amazon S3 allows you to restore deleted objects?', 2, 'A. S3 Transfer Acceleration,B. S3 Glacier,C. S3 Versioning,D. S3 Lifecycle Policies', 'AWS-CCP'),
('Which AWS service can help prevent Distributed Denial of Service (DDoS) attacks?', 1, 'A. Amazon VPC,B. AWS Shield,C. AWS Lambda,D. AWS S3', 'AWS-CCP'),
('What is the purpose of AWS CloudFormation?', 3, 'A. File storage,B. User authentication,C. Data analysis,D. Infrastructure as code', 'AWS-CCP'),
('Which AWS service offers a fully managed data warehouse solution?', 2, 'A. Amazon RDS,B. AWS S3,C. Amazon Redshift,D. AWS Lambda', 'AWS-CCP'),
('Which AWS service is primarily used for batch processing jobs?', 1, 'A. AWS Lambda,B. AWS Batch,C. Amazon S3,D. AWS Direct Connect', 'AWS-CCP'),
('What does Amazon RDS offer as its main functionality?', 3, 'A. Networking,B. File storage,C. Content delivery,D. Managed relational databases', 'AWS-CCP'),
('Which service enables organizations to set and manage security policies at scale across multiple AWS accounts?', 0, 'A. AWS Organizations,B. AWS Lambda,C. Amazon S3,D. AWS IAM', 'AWS-CCP'),
('What does AWS Trusted Advisor provide?', 2, 'A. Compute services,B. Direct connectivity,C. Best practices recommendations,D. Automated deployments', 'AWS-CCP'),
('Which service would you use to analyze and gain insights from streaming data in AWS?', 3, 'A. Amazon S3,B. AWS Lambda,C. Amazon EC2,D. Amazon Kinesis', 'AWS-CCP'),
('What is a key advantage of the AWS Well-Architected Framework?', 0, 'A. Provides best practices for building secure and high-performing systems,B. Offers data warehousing,C. Provides managed container orchestration,D. Delivers high-speed file storage', 'AWS-CCP'),
('Which service provides fully managed message queuing for microservices and decoupled applications?', 1, 'A. Amazon Kinesis,B. Amazon SQS,C. AWS Lambda,D. Amazon RDS', 'AWS-CCP'),
('What is the purpose of Amazon CloudWatch?', 0, 'A. Monitoring AWS resources,B. Data analytics,C. Object storage,D. Compute power', 'AWS-CCP'),
('Which AWS service provides automated machine learning model creation and deployment?', 2, 'A. AWS Lambda,B. AWS EC2,C. Amazon SageMaker,D. Amazon RDS', 'AWS-CCP'),
('What is the main use of Amazon DynamoDB?', 1, 'A. File storage,B. Managed NoSQL database,C. Virtual private network,D. Message queueing', 'AWS-CCP'),
('Which AWS service provides a fully managed, petabyte-scale data warehouse?', 2, 'A. Amazon S3,B. Amazon DynamoDB,C. Amazon Redshift,D. AWS Glue', 'AWS-CCP'),
('What is the primary benefit of AWS Auto Scaling?', 3, 'A. Data storage,B. Content delivery,C. User management,D. Automatic adjustment of capacity to meet demand', 'AWS-CCP'),
('Which AWS service is used to store and retrieve any amount of data at any time?', 0, 'A. Amazon S3,B. AWS Lambda,C. Amazon RDS,D. AWS CloudFront', 'AWS-CCP'),
('What is AWS Lambda used for?', 2, 'A. Managing databases,B. File storage,C. Running code without servers,D. Networking', 'AWS-CCP'),
('Which service provides a private connection from your on-premises network to AWS?', 3, 'A. Amazon EC2,B. Amazon S3,C. AWS Lambda,D. AWS Direct Connect', 'AWS-CCP'),
('What is the purpose of Amazon Route 53?', 0, 'A. Domain Name System (DNS) service,B. Database hosting,C. File storage,D. Monitoring', 'AWS-CCP'),
('Which service provides an interface to directly manage and organize AWS billing?', 1, 'A. Amazon S3,B. AWS Cost Explorer,C. AWS IAM,D. Amazon RDS', 'AWS-CCP'),
('Which AWS service is suitable for running code in response to events without managing servers?', 2, 'A. Amazon EC2,B. Amazon RDS,C. AWS Lambda,D. Amazon S3', 'AWS-CCP'),
('What is Amazon QuickSight used for?', 0, 'A. Business analytics,B. File storage,C. Managed database hosting,D. Domain Name System (DNS) service', 'AWS-CCP'),
('What AWS service helps manage access to AWS services and resources securely?', 1, 'A. AWS Lambda,B. AWS IAM,C. Amazon S3,D. Amazon EC2', 'AWS-CCP'),
('Which service provides long-term, low-cost data storage?', 3, 'A. Amazon EC2,B. AWS Lambda,C. Amazon S3,D. Amazon S3 Glacier', 'AWS-CCP'),
('What is the function of Amazon EBS?', 2, 'A. Networking,B. DNS management,C. Persistent block storage for EC2 instances,D. Data warehouse', 'AWS-CCP'),
('Which service allows users to set up a private network within the AWS cloud?', 0, 'A. Amazon VPC,B. AWS Lambda,C. Amazon CloudFront,D. Amazon S3', 'AWS-CCP'),
('What feature of Amazon S3 helps optimize costs for infrequently accessed data?', 3, 'A. S3 Transfer Acceleration,B. S3 Versioning,C. S3 Logging,D. S3 Storage Classes', 'AWS-CCP'),
('What is the purpose of AWS CloudTrail?', 1, 'A. Content delivery,B. Logging and tracking API calls,C. Object storage,D. Data warehousing', 'AWS-CCP'),
('Which AWS service allows users to create, manage, and host a domain name?', 3, 'A. AWS Lambda,B. Amazon EC2,C. Amazon S3,D. Amazon Route 53', 'AWS-CCP'),
('What type of database is Amazon DynamoDB?', 2, 'A. Relational,B. SQL-based,C. NoSQL,D. In-memory', 'AWS-CCP'),
('Which service is ideal for deploying and managing containers in AWS?', 0, 'A. Amazon ECS,B. Amazon S3,C. AWS Lambda,D. Amazon RDS', 'AWS-CCP'),
('Which AWS service can be used to run Spark, Hadoop, and other big data frameworks?', 1, 'A. AWS Lambda,B. Amazon EMR,C. AWS EC2,D. AWS RDS', 'AWS-CCP'),
('Which service is used to automate application deployment in a managed environment?', 3, 'A. Amazon RDS,B. Amazon VPC,C. AWS Lambda,D. AWS Elastic Beanstalk', 'AWS-CCP'),
('What is the primary function of Amazon S3 Transfer Acceleration?', 0, 'A. Speeding up content uploads to S3,B. DNS management,C. Database hosting,D. Monitoring application performance', 'AWS-CCP'),
('What AWS tool assists in analyzing and tracking AWS costs?', 1, 'A. AWS IAM,B. AWS Cost Explorer,C. Amazon RDS,D. Amazon DynamoDB', 'AWS-CCP'),
('Which AWS service offers a durable and secure location to store keys used to encrypt data?', 2, 'A. AWS IAM,B. AWS Lambda,C. AWS Key Management Service (KMS),D. Amazon S3', 'AWS-CCP'),
('Which AWS service allows for the transfer of data between on-premises data centers and AWS?', 3, 'A. Amazon S3,B. AWS Lambda,C. Amazon RDS,D. AWS Snowball', 'AWS-CCP'),
('Which Azure service is used to host and manage relational databases?', 2, 'A. Azure VMs,B. Azure App Service,C. Azure SQL Database,D. Azure Storage', 'AZ-900'),
('What is the main benefit of using Azure Blob Storage?', 3, 'A. Running VMs,B. Managing APIs,C. Hosting applications,D. Storing unstructured data', 'AZ-900'),
('Which Azure service provides tools for analyzing, processing, and managing big data?', 0, 'A. Azure Synapse Analytics,B. Azure Cosmos DB,C. Azure Key Vault,D. Azure AD', 'AZ-900'),
('Which service helps you monitor the performance and health of applications in Azure?', 1, 'A. Azure SQL Database,B. Azure Monitor,C. Azure Functions,D. Azure Storage', 'AZ-900'),
('Which Azure service is used to host and manage relational databases?', 2, 'A. Azure VMs,B. Azure App Service,C. Azure SQL Database,D. Azure Storage', 'AZ-900'),
('What is the primary benefit of using Azure Blob Storage?', 3, 'A. Running VMs,B. Managing APIs,C. Hosting applications,D. Storing unstructured data', 'AZ-900'),
('Which Azure service provides tools for analyzing, processing, and managing big data?', 0, 'A. Azure Synapse Analytics,B. Azure Cosmos DB,C. Azure Key Vault,D. Azure AD', 'AZ-900'),
('Which service helps you monitor the performance and health of applications in Azure?', 1, 'A. Azure SQL Database,B. Azure Monitor,C. Azure Functions,D. Azure Storage', 'AZ-900'),
('What is the purpose of Azure Active Directory?', 0, 'A. Identity and access management,B. Data analysis,C. Storage management,D. Big data processing', 'AZ-900'),
('Which Azure service allows you to create virtual machines?', 2, 'A. Azure Blob Storage,B. Azure Monitor,C. Azure Virtual Machines,D. Azure Functions', 'AZ-900'),
('What is Azure Kubernetes Service (AKS) primarily used for?', 3, 'A. Data storage,B. User authentication,C. Serverless functions,D. Container orchestration', 'AZ-900'),
('Which Azure service enables serverless computing?', 2, 'A. Azure Cosmos DB,B. Azure Virtual Machines,C. Azure Functions,D. Azure SQL Database', 'AZ-900'),
('Which Azure tool provides cost analysis and budgeting features?', 1, 'A. Azure Virtual Network,B. Azure Cost Management,C. Azure Active Directory,D. Azure Synapse Analytics', 'AZ-900'),
('What is Azure DevOps primarily used for?', 3, 'A. Data storage,B. Identity management,C. Virtual networking,D. CI/CD and project management', 'AZ-900'),
('What type of storage does Azure Table Storage provide?', 0, 'A. NoSQL storage,B. Block storage,C. Object storage,D. File storage', 'AZ-900'),
('Which Azure service provides a fully managed data warehouse?', 2, 'A. Azure Functions,B. Azure Blob Storage,C. Azure Synapse Analytics,D. Azure Kubernetes Service', 'AZ-900'),
('What is the purpose of Azure ExpressRoute?', 1, 'A. Public internet access,B. Private, dedicated network connection to Azure,C. Cloud storage management,D. Virtual machine management', 'AZ-900'),
('What is Azure Load Balancer used for?', 3, 'A. Storage management,B. Security management,C. CI/CD pipelines,D. Distributing network traffic evenly', 'AZ-900'),
('Which Azure service provides a scalable NoSQL database?', 0, 'A. Azure Cosmos DB,B. Azure SQL Database,C. Azure Synapse Analytics,D. Azure Virtual Machines', 'AZ-900'),
('What is the purpose of Azure Application Gateway?', 1, 'A. Identity management,B. Web application firewall and load balancing,C. Data warehousing,D. IoT management', 'AZ-900'),
('Which service helps you analyze data from multiple Azure sources in a centralized way?', 2, 'A. Azure Active Directory,B. Azure Virtual Network,C. Azure Synapse Analytics,D. Azure Blob Storage', 'AZ-900'),
('What does Azure Security Center primarily provide?', 3, 'A. Data processing,B. Network connectivity,C. Storage solutions,D. Security and threat protection', 'AZ-900'),
('What is the purpose of Azure Key Vault?', 1, 'A. Data storage,B. Securely store and manage keys, secrets, and certificates,C. Networking,D. Data analysis', 'AZ-900'),
('Which service would you use to build, train, and deploy machine learning models?', 3, 'A. Azure Functions,B. Azure Active Directory,C. Azure Synapse Analytics,D. Azure Machine Learning', 'AZ-900'),
('Which Azure service is used for real-time analytics?', 0, 'A. Azure Stream Analytics,B. Azure DevOps,C. Azure Monitor,D. Azure VMs', 'AZ-900'),
('What is Azure Logic Apps used for?', 1, 'A. Virtual networking,B. Workflow automation,C. Storage management,D. Data warehousing', 'AZ-900'),
('Which Azure service provides a secure and scalable data lake?', 3, 'A. Azure Virtual Machines,B. Azure DevOps,C. Azure SQL Database,D. Azure Data Lake Storage', 'AZ-900'),
('Which service provides domain name resolution in Azure?', 0, 'A. Azure DNS,B. Azure SQL Database,C. Azure Active Directory,D. Azure Cosmos DB', 'AZ-900'),
('What is the main use of Azure Virtual Network (VNet)?', 1, 'A. Data storage,B. Secure network isolation,C. File management,D. Application hosting', 'AZ-900'),
('Which service in Azure provides backup and disaster recovery?', 2, 'A. Azure SQL Database,B. Azure Active Directory,C. Azure Site Recovery,D. Azure Monitor', 'AZ-900'),
('What is the purpose of Azure Policy?', 3, 'A. Data storage,B. Serverless functions,C. IoT management,D. Enforcing organizational standards and assessing compliance', 'AZ-900'),
('Which Azure service allows hosting of static websites?', 0, 'A. Azure Blob Storage,B. Azure DevOps,C. Azure Monitor,D. Azure Kubernetes Service', 'AZ-900'),
('What type of service is Azure Firewall?', 1, 'A. Data analytics,B. Network security,C. File storage,D. Load balancing', 'AZ-900'),
('What is the purpose of Azure AD B2C?', 2, 'A. Storage,B. Data processing,C. Identity management for external customers,D. Container orchestration', 'AZ-900'),
('Which Azure service is best for IoT device management?', 3, 'A. Azure Cosmos DB,B. Azure Monitor,C. Azure Virtual Network,D. Azure IoT Hub', 'AZ-900'),
('What does Azure Traffic Manager help with?', 0, 'A. Distributing network traffic across multiple regions,B. Securing networks,C. Monitoring applications,D. Managing virtual machines', 'AZ-900'),
('Which service can be used to store JSON data in Azure?', 1, 'A. Azure Monitor,B. Azure Cosmos DB,C. Azure Virtual Machines,D. Azure DevOps', 'AZ-900'),
('Which Azure tool can be used to manage resources from a command line?', 2, 'A. Azure Synapse Analytics,B. Azure Functions,C. Azure CLI,D. Azure Active Directory', 'AZ-900'),
('What is the purpose of Azure Sentinel?', 3, 'A. Networking,B. File storage,C. Virtual machine hosting,D. Security information and event management (SIEM)', 'AZ-900'),
('Which Azure service provides a global content delivery network (CDN)?', 1, 'A. Azure AD,B. Azure CDN,C. Azure Kubernetes Service,D. Azure Blob Storage', 'AZ-900'),
('What does Azure Advisor provide recommendations for?', 2, 'A. Database management,B. IoT setup,C. Cost optimization and best practices,D. Network setup', 'AZ-900'),
('Which service enables hybrid cloud storage between on-premises and Azure?', 0, 'A. Azure File Sync,B. Azure Monitor,C. Azure Logic Apps,D. Azure DevOps', 'AZ-900'),
('What is the main purpose of Azure Resource Manager (ARM)?', 3, 'A. Security monitoring,B. Cost management,C. Data analysis,D. Resource deployment and management', 'AZ-900'),
('Which Azure service provides support for APIs, websites, and mobile backends?', 2, 'A. Azure Functions,B. Azure Virtual Machines,C. Azure App Service,D. Azure Data Lake', 'AZ-900'),
('What does Azure Bastion provide?', 1, 'A. Data backup,B. Secure RDP and SSH connectivity to virtual machines,C. Network traffic routing,D. Load balancing', 'AZ-900'),
('Which Azure service enables users to create workflows that integrate various systems?', 2, 'A. Azure DevOps,B. Azure Functions,C. Azure Logic Apps,D. Azure Blob Storage', 'AZ-900'),
('What is the purpose of the Azure Service Health service?', 3, 'A. Identity management,B. Data processing,C. Load balancing,D. Monitoring the health of Azure services and regions', 'AZ-900'),
('Which service would you use for secure, distributed ledger technology in Azure?', 0, 'A. Azure Blockchain Service,B. Azure Data Lake,C. Azure Cosmos DB,D. Azure Monitor', 'AZ-900'),
('What is Azure Cognitive Services used for?', 1, 'A. Virtual networking,B. Adding AI capabilities to applications,C. Database management,D. Serverless computing', 'AZ-900'),
('What does Azure Backup provide?', 2, 'A. CI/CD pipelines,B. Application insights,C. Backup and recovery of on-premises and Azure resources,D. Identity management', 'AZ-900'),
('What is the main purpose of Azure Virtual Desktop?', 0, 'A. Remote desktop infrastructure,B. Data storage,C. Network security,D. Load balancing', 'AZ-900'),
('Which service can help monitor security vulnerabilities in Azure?', 3, 'A. Azure DevOps,B. Azure Storage,C. Azure Active Directory,D. Azure Security Center', 'AZ-900'),
('Which Azure service is designed for high-performance computing workloads?', 1, 'A. Azure Virtual Network,B. Azure HPC Cluster Manager,C. Azure DevOps,D. Azure Kubernetes Service', 'AZ-900'),
('What does Azure Reservations allow users to do?', 2, 'A. Improve identity management,B. Configure network security,C. Reserve capacity for cost savings,D. Automate deployments', 'AZ-900'),
('What is the purpose of Azure Availability Zones?', 3, 'A. Database hosting,B. Network management,C. Security monitoring,D. Provide redundancy and high availability within a region', 'AZ-900'),
('Which service would you use to migrate databases to Azure?', 0, 'A. Azure Database Migration Service,B. Azure Logic Apps,C. Azure AD B2C,D. Azure Synapse Analytics', 'AZ-900'),
('What is the primary purpose of Azure Bot Service?', 1, 'A. Data storage,B. Building intelligent chatbots,C. Networking,D. Virtual machine hosting', 'AZ-900'),
('Which Azure service provides distributed, multi-model database capabilities?', 2, 'A. Azure SQL Database,B. Azure Data Lake Storage,C. Azure Cosmos DB,D. Azure Blob Storage', 'AZ-900'),
('What is the main benefit of using Azure Functions?', 3, 'A. Data warehousing,B. Data security,C. User identity,D. Running code without managing servers', 'AZ-900'),
('Which Azure tool helps developers track application performance in real time?', 0, 'A. Azure Application Insights,B. Azure AD,C. Azure Functions,D. Azure Kubernetes Service', 'AZ-900'),
('Which Azure service would be suitable for archiving infrequently accessed data?', 1, 'A. Azure SQL Database,B. Azure Blob Storage Archive Tier,C. Azure AD,D. Azure DevOps', 'AZ-900'),
('What does Azure Traffic Manager allow you to do?', 2, 'A. Identity and access management,B. Data storage,C. Distribute traffic to improve performance and availability,D. Container orchestration', 'AZ-900'),
('Which service provides a scalable solution for managing large sets of identity data in Azure?', 0, 'A. Azure AD B2C,B. Azure SQL Database,C. Azure Site Recovery,D. Azure Virtual Machines', 'AZ-900'),
('What type of encryption does Azure Storage use by default?', 3, 'A. Symmetric encryption,B. Triple DES,C. SSL only,D. AES-256 encryption', 'AZ-900'),
('Which service provides Azure-native support for machine learning operations?', 2, 'A. Azure DevOps,B. Azure Kubernetes Service,C. Azure Machine Learning,D. Azure Virtual Network', 'AZ-900'),
('What is the purpose of Azure Policy in governance?', 1, 'A. Resource scaling,B. Enforcing compliance and best practices,C. Load balancing,D. Data processing', 'AZ-900'),
('Which service offers a content delivery network (CDN) in Azure?', 0, 'A. Azure CDN,B. Azure Virtual Machines,C. Azure SQL Database,D. Azure Monitor', 'AZ-900'),
('What is the Azure Resource Manager (ARM) template used for?', 2, 'A. Analyzing data,B. Managing AD resources,C. Deploying resources consistently,D. Running virtual machines', 'AZ-900'),
('Which Azure service would you use to create a secure file-sharing solution?', 3, 'A. Azure Functions,B. Azure DevOps,C. Azure Machine Learning,D. Azure File Sync', 'AZ-900'),
('What does Azure Monitor provide?', 0, 'A. Insights and monitoring for resources,B. Database management,C. Serverless capabilities,D. Network isolation', 'AZ-900'),
('Which Azure tool would you use to manage, deploy, and troubleshoot containers?', 1, 'A. Azure Functions,B. Azure Kubernetes Service (AKS),C. Azure Blob Storage,D. Azure AD', 'AZ-900'),
('What is the main purpose of Azure DDoS Protection?', 3, 'A. Serverless computing,B. Data management,C. Cost management,D. Mitigating DDoS attacks on Azure resources', 'AZ-900'),
('Which service would be best for real-time data ingestion and analytics?', 0, 'A. Azure Stream Analytics,B. Azure Blob Storage,C. Azure DevOps,D. Azure AD', 'AZ-900'),
('What is the purpose of Azure Blueprints?', 1, 'A. Data storage,B. Predefined templates for resource governance and compliance,C. Load balancing,D. Virtual networking', 'AZ-900'),
('Which service allows you to orchestrate and automate cloud tasks?', 2, 'A. Azure Cosmos DB,B. Azure SQL Database,C. Azure Logic Apps,D. Azure Functions', 'AZ-900'),
('What does Azure Key Vault primarily provide?', 3, 'A. Serverless functions,B. Monitoring capabilities,C. File storage,D. Secure storage for secrets, keys, and certificates', 'AZ-900'),
('Which service helps you create, deploy, and scale apps in Azure without managing infrastructure?', 0, 'A. Azure App Service,B. Azure Synapse Analytics,C. Azure Virtual Machines,D. Azure Cosmos DB', 'AZ-900'),
('What does Azure Identity Protection help with?', 2, 'A. Cost management,B. Data storage,C. Detecting and responding to identity risks,D. Managing compliance', 'AZ-900'),
('Which Azure feature allows you to control network traffic in a virtual network?', 3, 'A. Azure DevOps,B. Azure Functions,C. Azure Monitor,D. Network Security Groups (NSGs)', 'AZ-900'),
('What is Azure Cost Management used for?', 1, 'A. Data analysis,B. Monitoring and controlling Azure spending,C. Server management,D. Secure data transfer', 'AZ-900'),
('Which Google Cloud service provides scalable object storage?', 0, 'A. Google Cloud Storage,B. Google BigQuery,C. Google Compute Engine,D. Google App Engine', 'GCP-ACE'),
('What is the purpose of Google Kubernetes Engine (GKE)?', 1, 'A. Serverless functions,B. Orchestrating containers,C. Managing relational databases,D. Data analysis', 'GCP-ACE'),
('Which Google Cloud service allows for real-time data processing and analysis?', 3, 'A. Cloud SQL,B. Google Cloud Storage,C. Google Compute Engine,D. Google Dataflow', 'GCP-ACE'),
('What is Google BigQuery primarily used for?', 0, 'A. Data warehousing,B. File storage,C. Running virtual machines,D. Developing mobile applications', 'GCP-ACE'),
('What is the purpose of Google Cloud Identity and Access Management (IAM)?', 2, 'A. Networking,B. Data storage,C. Access control and permissions,D. Machine learning', 'GCP-ACE'),
('Which service allows you to host scalable web applications on Google Cloud?', 1, 'A. Cloud Functions,B. App Engine,C. Cloud Bigtable,D. Cloud Storage', 'GCP-ACE'),
('What does Google Cloud Storage provide?', 0, 'A. Object storage,B. Container orchestration,C. Virtual machine hosting,D. Machine learning', 'GCP-ACE'),
('Which command-line tool is used to interact with Google Cloud resources?', 2, 'A. AWS CLI,B. Azure CLI,C. gcloud CLI,D. kubectl', 'GCP-ACE'),
('What is the primary purpose of Google Cloud Pub/Sub?', 3, 'A. Virtual machine management,B. File storage,C. Container hosting,D. Messaging and event ingestion', 'GCP-ACE'),
('What is Google Kubernetes Engine (GKE) used for?', 1, 'A. Data analysis,B. Managing and deploying containers,C. Identity management,D. Load balancing', 'GCP-ACE'),
('Which database service provides a fully managed NoSQL database on Google Cloud?', 2, 'A. Cloud SQL,B. Cloud Spanner,C. Firestore,D. BigQuery', 'GCP-ACE'),
('What does Google Cloud BigQuery primarily provide?', 0, 'A. Data warehousing and analytics,B. Web hosting,C. Container management,D. Identity management', 'GCP-ACE'),
('Which service would you use to build, deploy, and scale APIs on Google Cloud?', 3, 'A. Cloud Bigtable,B. Cloud Storage,C. Cloud SQL,D. Apigee', 'GCP-ACE'),
('What does Cloud Interconnect provide?', 1, 'A. Machine learning,B. High-speed, private connectivity between Google Cloud and on-premises resources,C. Data warehousing,D. Virtual machine hosting', 'GCP-ACE'),
('Which Google Cloud service is designed for running serverless code in response to events?', 2, 'A. Compute Engine,B. Cloud Storage,C. Cloud Functions,D. Cloud SQL', 'GCP-ACE'),
('What is the purpose of Google Cloud Monitoring?', 3, 'A. Data storage,B. Machine learning,C. Identity management,D. Observing and tracking system performance', 'GCP-ACE'),
('Which storage class in Google Cloud Storage is most suitable for infrequently accessed data?', 1, 'A. Regional,B. Coldline,C. Standard,D. Multi-Regional', 'GCP-ACE'),
('What is Cloud SQL primarily used for?', 0, 'A. Managed relational databases,B. Event processing,C. Virtual machine hosting,D. API management', 'GCP-ACE'),
('Which Google Cloud service helps protect against DDoS attacks?', 3, 'A. Cloud Storage,B. App Engine,C. Cloud SQL,D. Cloud Armor', 'GCP-ACE'),
('Which tool allows you to manage configurations in Google Cloud using YAML files?', 0, 'A. Deployment Manager,B. Cloud Functions,C. App Engine,D. BigQuery', 'GCP-ACE'),
('What is the main purpose of Google Cloud VPC (Virtual Private Cloud)?', 1, 'A. Identity management,B. Network isolation and control,C. Data warehousing,D. Machine learning', 'GCP-ACE'),
('Which Google Cloud service would you use to deploy containers?', 2, 'A. Cloud Storage,B. Cloud SQL,C. Google Kubernetes Engine (GKE),D. Cloud Functions', 'GCP-ACE'),
('What does Google Cloud Load Balancing provide?', 3, 'A. Data processing,B. Machine learning,C. API management,D. Distribution of incoming traffic across multiple resources', 'GCP-ACE'),
('Which service would you use for data streaming in Google Cloud?', 0, 'A. Cloud Pub/Sub,B. Cloud SQL,C. App Engine,D. Cloud Spanner', 'GCP-ACE'),
('What is the purpose of Google Cloud Dataflow?', 1, 'A. Storing data,B. Processing streaming and batch data,C. Hosting applications,D. Identity management', 'GCP-ACE'),
('Which Google Cloud service is used to store large datasets in a NoSQL format?', 2, 'A. Cloud SQL,B. Cloud Spanner,C. Bigtable,D. Dataflow', 'GCP-ACE'),
('What does the "gcloud compute instances create" command do?', 3, 'A. Creates a database,B. Deploys an application,C. Configures IAM roles,D. Creates a virtual machine instance', 'GCP-ACE'),
('Which tool would you use to monitor Google Cloud resources and set up alerts?', 0, 'A. Cloud Monitoring,B. BigQuery,C. Cloud Pub/Sub,D. Cloud Run', 'GCP-ACE'),
('What is the purpose of Google Cloud Run?', 1, 'A. Managing VMs,B. Running containerized applications without managing infrastructure,C. Data analysis,D. Security', 'GCP-ACE'),
('Which Google Cloud service offers data encryption and key management?', 2, 'A. Cloud Spanner,B. Cloud Storage,C. Cloud KMS,D. Cloud SQL', 'GCP-ACE'),
('What does Google Cloud IAM allow administrators to do?', 3, 'A. Network management,B. Big data processing,C. Virtual machine hosting,D. Assign and control permissions on resources', 'GCP-ACE'),
('Which Google Cloud service provides a managed database for relational data?', 1, 'A. Bigtable,B. Cloud SQL,C. Cloud Functions,D. Dataflow', 'GCP-ACE'),
('What does Google Cloud Operations Suite offer?', 2, 'A. Managed databases,B. Container orchestration,C. Monitoring, logging, and diagnostics,D. Virtual networking', 'GCP-ACE'),
('What is the purpose of Cloud Armor?', 3, 'A. Identity management,B. Data storage,C. Analytics,D. Security policies and protection against DDoS attacks', 'GCP-ACE'),
('Which storage class is suitable for long-term storage with low access frequency in Google Cloud?', 0, 'A. Archive,B. Standard,C. Regional,D. Multi-Regional', 'GCP-ACE'),
('What does Cloud Spanner provide?', 1, 'A. Batch processing,B. Globally distributed relational database service,C. Messaging,D. Object storage', 'GCP-ACE'),
('Which service would you use for a serverless data warehouse in Google Cloud?', 2, 'A. Cloud SQL,B. Cloud Functions,C. BigQuery,D. Cloud Storage', 'GCP-ACE'),
('Which Google Cloud service can manage machine learning models?', 3, 'A. Cloud Functions,B. Cloud Storage,C. App Engine,D. AI Platform', 'GCP-ACE'),
('What is the purpose of Google Cloud Interconnect?', 0, 'A. High-bandwidth connection from on-premises to Google Cloud,B. Data encryption,C. Load balancing,D. Monitoring', 'GCP-ACE'),
('Which command in Google Cloud CLI is used to deploy applications on App Engine?', 1, 'A. gcloud compute instances create,B. gcloud app deploy,C. gcloud iam roles list,D. gcloud pubsub topics create', 'GCP-ACE'),
('What is Cloud Composer used for?', 2, 'A. Machine learning,B. Virtual networking,C. Orchestrating workflows with Apache Airflow,D. API management', 'GCP-ACE'),
('Which service provides highly scalable in-memory data caching for applications?', 3, 'A. BigQuery,B. Cloud SQL,C. Cloud Functions,D. Memorystore', 'GCP-ACE'),
('What is the main function of Google Cloud CDN?', 0, 'A. Content delivery network for low-latency access,B. Data storage,C. Virtual machine hosting,D. Data analysis', 'GCP-ACE'),
('What does the gcloud config set project command do?', 1, 'A. Deploys resources,B. Sets the default project,C. Lists VM instances,D. Creates a storage bucket', 'GCP-ACE'),
('Which service provides automated backups and point-in-time recovery for databases?', 2, 'A. Cloud Storage,B. Cloud IAM,C. Cloud SQL,D. BigQuery', 'GCP-ACE'),
('What is the primary function of Google Cloud VPN?', 3, 'A. Data analysis,B. Running VMs,C. Data processing,D. Establishing secure connections between on-premises networks and Google Cloud', 'GCP-ACE'),
('What is Cloud Endpoints used for?', 0, 'A. API management,B. Networking,C. Data warehousing,D. Monitoring', 'GCP-ACE'),
('What is the purpose of BigQuery Data Transfer Service?', 1, 'A. Running serverless functions,B. Automating data transfers into BigQuery from SaaS applications,C. Managing VMs,D. Cloud storage', 'GCP-ACE'),
('What does Google Cloud NAT do?', 2, 'A. Data analysis,B. Identity management,C. Provides internet access for private instances,D. Data storage', 'GCP-ACE'),
('Which service helps you create and deploy containerized applications easily?', 3, 'A. Cloud Pub/Sub,B. Cloud SQL,C. Bigtable,D. Cloud Run', 'GCP-ACE'),
('Which tool helps with identity management in Google Cloud?', 0, 'A. Cloud Identity,B. Cloud Storage,C. Cloud Functions,D. Dataflow', 'GCP-ACE'),
('What does Google Cloud Logging provide?', 1, 'A. Relational database hosting,B. Collection and analysis of log data,C. Machine learning model deployment,D. Virtual networking', 'GCP-ACE'),
('What is the primary purpose of Google Cloud Filestore?', 2, 'A. Managing secrets,B. Running containers,C. File storage for applications,D. Streaming data', 'GCP-ACE'),
('What is the primary use of Google Cloud Firestore?', 1, 'A. Machine learning,B. NoSQL document database,C. Object storage,D. Load balancing', 'GCP-ACE'),
('What is the main purpose of Google Cloud Deployment Manager?', 2, 'A. Monitoring resources,B. Data analytics,C. Automating the deployment of Google Cloud resources,D. Database management', 'GCP-ACE'),
('What is Google Cloud Identity primarily used for?', 3, 'A. Virtual machine hosting,B. Data warehousing,C. Security and data encryption,D. Centralized identity and access management', 'GCP-ACE'),
('Which Google Cloud service is designed for executing code based on triggers from HTTP requests or other events?', 0, 'A. Cloud Functions,B. Cloud Storage,C. Cloud SQL,D. BigQuery', 'GCP-ACE'),
('What is the main advantage of using Google Cloud Memorystore?', 1, 'A. Data encryption,B. Caching for fast data access,C. Data warehousing,D. Server management', 'GCP-ACE'),
('Which service would be best for storing large analytical datasets in Google Cloud?', 2, 'A. Cloud SQL,B. Cloud Storage,C. BigQuery,D. Cloud Spanner', 'GCP-ACE'),
('What is Google Cloud Transfer Appliance used for?', 3, 'A. Cloud monitoring,B. Identity management,C. Data analysis,D. Physically transferring large data volumes to Google Cloud', 'GCP-ACE'),
('What does Google Cloud Dataproc provide?', 0, 'A. Managed Spark and Hadoop processing,B. Container management,C. Object storage,D. Virtual networking', 'GCP-ACE'),
('Which service helps manage encryption keys in Google Cloud?', 1, 'A. Cloud Monitoring,B. Cloud Key Management Service (KMS),C. Cloud Datastore,D. BigQuery', 'GCP-ACE'),
('What is the primary use of Google Cloud Filestore?', 2, 'A. Database management,B. Message queuing,C. File storage for applications,D. API management', 'GCP-ACE'),
('What type of database is Google Cloud Bigtable primarily used for?', 3, 'A. Relational,B. Document,C. Graph,D. Wide-column NoSQL', 'GCP-ACE'),
('Which command in Google Cloud CLI is used to view all compute instances in a project?', 0, 'A. gcloud compute instances list,B. gcloud app deploy,C. gcloud config set project,D. gcloud storage buckets create', 'GCP-ACE'),
('Which Google Cloud tool enables interactive and automated configuration and management of cloud resources?', 1, 'A. Cloud Functions,B. Terraform,C. Cloud Run,D. BigQuery', 'GCP-ACE'),
('What is the purpose of Google Cloud Logging?', 2, 'A. Running machine learning models,B. Data storage,C. Centralized collection and analysis of logs,D. Data transfer', 'GCP-ACE'),
('Which service provides a virtual private cloud (VPC) in Google Cloud?', 3, 'A. Cloud SQL,B. BigQuery,C. Cloud Run,D. Google Cloud VPC', 'GCP-ACE'),
('What is Google Cloud Secret Manager used for?', 1, 'A. Managing containers,B. Storing and managing access to sensitive data like API keys,C. Data warehousing,D. Monitoring logs', 'GCP-ACE'),
('What is the main purpose of Cloud Router?', 2, 'A. Hosting websites,B. Security management,C. Dynamic routing for hybrid and multi-cloud networks,D. Running containers', 'GCP-ACE'),
('What is the role of Google Cloud Armor?', 3, 'A. Container management,B. File storage,C. Machine learning,D. DDoS protection and security policies', 'GCP-ACE'),
('Which Google Cloud service offers fully managed Hadoop and Spark clusters?', 0, 'A. Cloud Dataproc,B. BigQuery,C. Cloud SQL,D. Cloud Run', 'GCP-ACE'),
('What type of storage does Google Cloud Filestore provide?', 1, 'A. Object storage,B. Managed file storage for applications,C. Document database,D. In-memory caching', 'GCP-ACE'),
('What is the purpose of Google Cloud Virtual Private Cloud (VPC)?', 2, 'A. File storage,B. Data warehousing,C. Network management and isolation,D. Serverless computing', 'GCP-ACE'),
('Which Google Cloud tool helps with serverless CI/CD for applications?', 3, 'A. Cloud Spanner,B. Cloud SQL,C. Bigtable,D. Cloud Build', 'GCP-ACE'),
('Which service is best suited for migrating existing VMs to Google Cloud?', 0, 'A. Migrate for Compute Engine,B. Cloud Functions,C. Cloud Run,D. BigQuery', 'GCP-ACE'),
('What does Google Cloud Traffic Director provide?', 1, 'A. Data storage,B. Global traffic management and service mesh,C. Big data processing,D. Serverless functions', 'GCP-ACE'),
('Which Google Cloud service provides automated machine learning (AutoML) capabilities?', 2, 'A. Cloud SQL,B. Cloud Dataproc,C. AI Platform,D. Cloud Functions', 'GCP-ACE'),
('What is the primary function of Google Cloud Resource Manager?', 3, 'A. Managing APIs,B. Data warehousing,C. Networking,D. Organizing and managing project hierarchies and permissions', 'GCP-ACE'),
('Which Google Cloud product would you use to create and run Docker containers?', 0, 'A. Cloud Run,B. Cloud SQL,C. BigQuery,D. Cloud Spanner', 'GCP-ACE'),
('What does Google Cloud Interconnect provide?', 1, 'A. Serverless computing,B. High-speed connectivity between on-premises networks and Google Cloud,C. Database management,D. Data warehousing', 'GCP-ACE'),
('What is the purpose of Google Cloud Transfer Service?', 2, 'A. Data encryption,B. Resource management,C. Moving large data volumes between Google Cloud and other cloud providers,D. Application development', 'GCP-ACE'),
('Which service offers a managed data warehouse on Google Cloud?', 3, 'A. Cloud Functions,B. Bigtable,C. Cloud Spanner,D. BigQuery', 'GCP-ACE'),
('What is the role of Google Cloud API Gateway?', 0, 'A. Manage and secure APIs,B. Store secrets,C. Data encryption,D. Manage VMs', 'GCP-ACE'),
('Which command-line tool is used to manage Google Kubernetes Engine (GKE) clusters?', 1, 'A. gcloud,B. kubectl,C. terraform,D. ansible', 'GCP-ACE'),
('What is Google Cloud CloudShell?', 2, 'A. A container service,B. A data storage service,C. An interactive shell environment to manage cloud resources,D. A VM management tool', 'GCP-ACE'),
('What does Google Cloud Endpoints provide?', 3, 'A. Machine learning,B. Networking,C. Object storage,D. API management and deployment', 'GCP-ACE'),
('What is the primary function of Google Cloud Scheduler?', 0, 'A. Task scheduling and automation,B. Object storage,C. Running containers,D. Managing relational databases', 'GCP-ACE'),
('Which tool is recommended for managing infrastructure as code on Google Cloud?', 1, 'A. Cloud SQL,B. Terraform,C. BigQuery,D. App Engine', 'GCP-ACE'),
('What does Google Cloud VPC Flow Logs enable you to monitor?', 2, 'A. API calls,B. Application errors,C. Network traffic within VPC,D. Virtual machine status', 'GCP-ACE'),
('What type of data does Google Cloud BigQuery support?', 3, 'A. Object data,B. Block data,C. File data,D. Structured and semi-structured data', 'GCP-ACE'),
('Which tool would you use to manage API access control in Google Cloud?', 0, 'A. Cloud IAM,B. Cloud SQL,C. Cloud Spanner,D. BigQuery', 'GCP-ACE'),
('What is the purpose of Google Cloud Console?', 1, 'A. Running machine learning models,B. Web-based interface for managing cloud resources,C. Deploying VMs,D. Storing data', 'GCP-ACE'),
('What type of resource can you create with Cloud Deployment Manager?', 2, 'A. Machine learning models,B. Data storage,C. Compute, network, and storage resources,D. VPC configurations', 'GCP-ACE'),
('Which Google Cloud product provides a global content delivery network?', 3, 'A. Cloud SQL,B. BigQuery,C. Cloud Datastore,D. Cloud CDN', 'GCP-ACE'),
('What is the purpose of Google Cloud Recommender?', 0, 'A. Provide cost-saving and security recommendations,B. Store API keys,C. Host machine learning models,D. Secure virtual networks', 'GCP-ACE'),
('Which service offers high-speed data transfer from on-premises to Google Cloud?', 1, 'A. Cloud Functions,B. Cloud Interconnect,C. BigQuery,D. Cloud Datastore', 'GCP-ACE'),
('What does Google Cloud Service Directory provide?', 2, 'A. Data encryption,B. Cloud resource monitoring,C. Centralized registry for services,D. Load balancing', 'GCP-ACE'),
('What is the purpose of Cloud Build?', 3, 'A. Data warehousing,B. Network configuration,C. File storage,D. CI/CD for building and deploying applications', 'GCP-ACE');